openapi: 3.0.0
info:
  title: Math API
  description: A simple REST API for performing mathematical operations on two numbers.
  version: 1.0.0
servers:
- url: https://app.swaggerhub.com/apis/LisharBahar/matrix-assigment-api/1.0.0
paths:
  /math:
    post:
      summary: Perform a mathematical operation on two numbers
      operationId: mathPOST
      parameters:
      - name: operation
        in: header
        description: "The mathematical operation to perform (e.g., add, subtract, multiply, divide)"
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/math_body'
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
      security:
      - bearerAuth: []
      x-swagger-router-controller: MathController
components:
  schemas:
    math_body:
      type: object
      properties:
        num1:
          type: number
          description: The first number
        num2:
          type: number
          description: The second number
    inline_response_200:
      type: object
      properties:
        result:
          type: number
          description: The result of the mathematical operation
      example:
        result: 0.80082819046101150206595775671303272247314453125
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
